name: Truffle Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-install:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup NodeJS 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Show NodeJS version    
      run: npm --version
    
    - name: Install Truffle
      working-directory: ./Trustify
      run: npm install truffle@5.5.22 -g # cannot use truffle@latest due to https://github.com/sc-forks/solidity-coverage/issues/696
    
    - name: Install Truffle Dependencies
      working-directory: ./Trustify
      run: npm install
      
  run-ganache:
    runs-on: ubuntu-latest
    needs: [build-and-install]
    steps:
    - uses: actions/checkout@v2
    - name: Start ganache blockchain
      working-directory: ./Trustify
      run: npx ganache
      
  run-test:
    runs-on: ubuntu-latest
    needs: [build-and-install, run-ganache]
    steps:    
    - uses: actions/checkout@v2
    - name: Run Truffle Test with CI=true for Codechecks 
      working-directory: ./Trustify
      run: CI=true truffle test
